# Data and Model
info_path: "output/data/train.data"
model_path: "output/models"
similarity_probability: 0.35
batches_per_epoch: null

# Logging
use_wandb: False
use_tqdm: True

# Model Hyperparameters
epochs: 15
latent_space_size: 512
batch_size: 16
test_batch_size: 16
test_batch_count: 8
save_model_every: 50
early_stopping_epochs: 15
cross_validiton_k_fold: 1

# Optimizer
optimizer: "adamw"
optimizer_params:
  lr: 3e-4
  weight_decay: 0.01

# Optional: Scheduler
lr_scheduler: "cosine"
lr_warmup_steps: 500

# Contrastive loss
contrastive_margin: 0.9
contrastive_epsilon: 1.0e-8